### PR TITLE
revert changes introduced in EA3835 to audio sink auto-select, fixing stuttering in Diablo 3, etc

### PR DESCRIPTION
**Pull request by mateomaui**
Reverts most of this commit (but not all, some parts are still needed, or were reverted already in later EAs): https://github.com/litucks/torzu/commit/39c8ddcda281e5f5b125c78b55741e39a50ff254?style=split&whitespace=show-all&show-outdated= or http://vub63vv26q6v27xzv2dtcd25xumubshogm67yrpaz2rculqxs7jlfqad.onion/torzu-emu/torzu/commit/39c8ddcda281e5f5b125c78b55741e39a50ff254?style=split&whitespace=show-all&show-outdated=

Above commit to the audio sink was first included in EA-3835, changing the way an audio engine is auto-selected by lowest latency... but still doesn't work very well, often using cubeb when it should use SDL.

A side effect of this was that microstuttering was introduced in a few titles. In Diablo 3, the main player character appears to teleport forward a few steps, every couple of steps. It's a consistent, constant stutter when simply walking forward. Occurs for both SDL and cubeb, with cubeb noticeably worse.

3834 and 3833 didn't have this issue with SDL, and the commit above was the bulk of the changes for 3835. Reverting those changes back to the 3833 version has fixed the stutter (for me at least) in D3 as long as SDL is selected (cubeb still stutters). The only observed negative is the audio engine may need to be manually selected in global settings instead of using auto.

Also seems to have fixed intermittent microstutters in TOTK and RDR. Unaware of other titles this may fix, or possibly create a problem for (though creating issues probably is not likely.)

### CODE REVIEW

**Comment by litucks** [comment]
Have verified this actually fixes audio stutter. Thank you very much! Will merge soon.

**Comment by litucks** [comment]
Please make sure to have a copy!!!

```
Hi litucks,

GitHub Trust & Safety is contacting you because we've received a DMCA takedown notice regarding the following content:

https://github.com/litucks/torzu

You can see the DMCA takedown notice that we received here, which includes the complainant's requested changes to your repository:

https://enterprise.githubsupport.com/attachments/token/IRkbmN2s4Pu7U7fwBNZ2hXYoP/?name=2024-07-05-nintendo.rtf

We want to make clear that it is never our desire or goal to take down open source projects, but instead to help developers address DMCA concerns with their projects. To that end, you have some options:

1. If you choose to make changes in response to this takedown notice, you'll have 1 business day to make the requested changes. Once you've made the changes, please reply to this message and let us know. If you don't tell us that you've made changes within the next 1 business day, we'll need to disable the entire repository according to our GitHub DMCA Takedown Policy - https://docs.github.com/en/github/site-policy/dmca-takedown-policy

If you need to remove specific content from your repository, simply making the repository private or deleting it via a commit won't resolve the alleged infringement. Instead, you must follow these instructions to remove the content from your repository's history, even if you don't think it's sensitive - https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/removing-sensitive-data-from-a-repository

2. If you believe your content on GitHub was mistakenly identified by a DMCA takedown request, you have the right to contest the takedown by submitting a counter notice, as described in our DMCA Takedown Policy - https://docs.github.com/en/github/site-policy/dmca-takedown-policy

We want to help ensure you can make informed decisions when responding to this takedown request. To help, we have partnered with leading legal providers who can help you evaluate the takedown request and determine how to respond at no cost to you. If you are interested in receiving legal support through this program (https://github.blog/2021-07-27-github-developer-rights-fellowship-stanford-law-school/), reply to this message to let us know that.

It is important that you reply to this message within 1 business day regardless of which option you choose. If you do not, the repository will be disabled.

Please let us know if you have any questions or need any help removing the content.

Regards,
GitHub Trust & Safety
```

**Comment by mateomaui** [comment]
Notice noted.

Also noted that sudachi is included in that same takedown notice.
```
**What files should be taken down? Please provide URLs for each file, or if the entire repository, the repository’s URL.**

https://github.com/CCIGAMES/suyu    
https://github.com/zhongfly/yuzu-build    
https://github.com/litucks/torzu    
https://github.com/CloudCorpRecords/yuzu_compressed    
https://github.com/suyu-emu/suyu    
https://github.com/ImpXada/Auto-CI    
https://github.com/Aphcity/suyu    
https://github.com/sudachi-emu/sudachi   
```

**Comment by mateomaui** [comment]
> Have verified this actually fixes audio stutter.

I wasn't actually aware of that detail yet. It makes sense, but I only was aware of video stutter caused by it. Good to know, thanks for including it!

**Pull request merged**
