### PR TITLE
Diablo3 fix

### PR DESCRIPTION
**Pull request by mateomaui**
Reverts most of this commit (but not all, some parts are still needed, or were reverted already in later EAs): https://github.com/litucks/torzu/commit/39c8ddcda281e5f5b125c78b55741e39a50ff254?style=split&whitespace=show-all&show-outdated= or http://vub63vv26q6v27xzv2dtcd25xumubshogm67yrpaz2rculqxs7jlfqad.onion/torzu-emu/torzu/commit/39c8ddcda281e5f5b125c78b55741e39a50ff254?style=split&whitespace=show-all&show-outdated=

Above commit to the audio sink was first included in EA-3835 (https://app.radicle.xyz/nodes/seed.radicle.garden/rad:z2LMLbRcQGxwTU7iDa2kwHqYYafu5/commits/17bf9b7d23d736bda7467bd735e6abe05cf7d30a), intended to change the way the emulator auto-selects an audio source with the lowest latency... but still (in my opinion) doesn't actually work very well, for me it still often uses cubeb, when it should use SDL.

The side effect of this is that microstuttering was introduced in a few titles. The one that led me to this was Diablo 3, where (at least on my hardware) the main player character appears to teleport forward a few steps, every couple of steps. It's a consistent, constant stutter when simply walking forward. Occurs when either SDL or cubeb is selected as audio source, noticeably worse for cubeb, but doesn't happen at all with null selected. 

Going backwards through EA versions, 3834 and 3833 were the newest that didn't have this issue for SDL (3834 were only Android changes), and the commit above was the bulk of the changes for 3835. Reverting those audio sync changes back to the 3833 version has fixed the stutter for me in D3 as long as SDL is selected (cubeb is improved but still stutters), and as far as I can tell, the only negative is that you'll probably have to manually select the proper audio engine in global settings instead of using auto, which wasn't much of a change for me since auto would keep using the wrong engine anyway.

Reverting also seems to have fixed intermittent microstutters for me in TOTK and RDR. I am unaware of other titles this may fix, or possibly create a problem for (though creating issues probably is not likely.)

### CODE REVIEW

**Comment by mateomaui** [comment]
There appears to be a new cmake error related to the vcpkg update. Closing this until that's sorted, will resubmit.

**Comment by litucks** [comment]
Thank you very much for the contribution though :-)
If possible please make sure to keep the commit history somewhat clean so I don't have to squash your commits.

**Comment by mateomaui** [comment]
Doing my best to keep it clean, not sure how to update the branch with already merged changes without a small amount of clutter though.

**Comment by litucks** [comment]
It's alright, appreciate your efforts either way :+1:

**Comment by litucks** [comment]
PLEASE BE SURE to back up your repository, as a DMCA claim for this repo is VERY LIKELY incoming (I've received messages about the files on Mega being DMCA claimed)!!

In case this repository gets taken down before I've accepted your PR, please resubmit your PR on the new mirror repo!

It's going to be located at: https://codeberg.org/litucks/torzu

**Comment by mateomaui** [comment]
Oh, no worries about my repos, all my dev ones are on a local Rpi forgejo instance. I just duplicate changes to my github copy when I have a solution.

**Pull request closed without merging**
