### PR TITLE
Replace non-existent repos for windows binaries (etc) in CMakeLists.txt and DownloadExternals.cmake - but there's still a build problem on Windows

### PR DESCRIPTION
**Pull request by mateomaui**
NOTE: Aside from the changes suggested, I wasn't sure how to submit the info about the build error now, except via the same pull request.

Fixing the non-existent repo paths _(from "yuzu-emu" and "torzu" to "litucks"... or could use "yuzu-mirror" if there have been no changes to the ext-*****-bin repos)_ corrected some download errors, but CMake configuring still fails with the following:

> -- Looking for include file android/log.h
> -- Looking for include file android/log.h - not found
> -- Looking for include file sys/audioio.h
> -- Looking for include file sys/audioio.h - not found
> -- Looking for include file kai.h
> -- Looking for include file kai.h - not found
> -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
> CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
>   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
>   OPENSSL_INCLUDE_DIR Crypto SSL) (Required is at least version "1.1.1")
> Call Stack (most recent call first):
>   C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
>   C:/Program Files/CMake/share/cmake-3.29/Modules/FindOpenSSL.cmake:686 (find_package_handle_standard_args)
>   externals/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
>   externals/cpp-httplib/CMakeLists.txt:118 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!

Haven't been able to figure out what's causing this yet. (For what it's worth, I'm used to successfully compiling yuzu and sudachi without issues.)

This was my cmake CLI command 
`cmake -E env CXXFLAGS="/Gw" cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_POLICY_DEFAULT_CMP0069=NEW -DYUZU_ENABLE_LTO=ON -DYUZU_USE_BUNDLED_QT=1 -DYUZU_USE_BUNDLED_SDL2=1 -DYUZU_USE_QT_WEB_ENGINE=ON -DYUZU_TESTS=OFF -DENABLE_QT_TRANSLATION=ON -DENABLE_CUBEB=ON -DENABLE_LIBUSB=ON -DENABLE_WEB_SERVICE=ON -DUSE_DISCORD_PRESENCE=OFF -DYUZU_ROOM=ON -DCMAKE_BUILD_TYPE=Release ..`

### CODE REVIEW

**Comment by mateomaui** [comment]
NOTE: I wasn't sure how to submit any of this now, except via a pull request

**Comment by mateomaui** [comment]
This was my cmake CLI command 
`
cmake -E env CXXFLAGS="/Gw" cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_POLICY_DEFAULT_CMP0069=NEW -DYUZU_ENABLE_LTO=ON -DYUZU_USE_BUNDLED_QT=1 -DYUZU_USE_BUNDLED_SDL2=1 -DYUZU_USE_QT_WEB_ENGINE=ON -DYUZU_TESTS=OFF -DENABLE_QT_TRANSLATION=ON -DENABLE_CUBEB=ON -DENABLE_LIBUSB=ON -DENABLE_WEB_SERVICE=ON -DUSE_DISCORD_PRESENCE=OFF -DYUZU_ROOM=ON -DCMAKE_BUILD_TYPE=Release ..`

**Comment by litucks** [comment]
Hi! I haven't had that OpenSSL build error when building for Windows so far.
But I've seen it before. You could try with this specific version of OpenSSL: https://slproweb.com/download/Win64OpenSSL-3_3_1.exe
That's the one I've been using I think.

**Comment by litucks** [comment]
Thank you for the pull request :+1:

**Comment by mateomaui** [comment]
Thank you for the reply! 

If we can get these build errors sorted out, I also have a fix for stuttering player character movement in Diablo 3 (and some other games) related to one audio sink commit (which works in EA4176), but before I submit a pull request I have to be able to build torzu and test it first: https://github.com/litucks/torzu/compare/master...mateomaui:torzu:Diablo3Fix (reverting this commit https://github.com/litucks/torzu/commit/39c8ddc)

So I downloaded and installed that version of OpenSSL, which got it past that original error. I'm not sure why I would need to manually and install that now, but ok.

However, now there is a problem with QT... when I git a fresh copy of the repo, git dependencies and run my usual CMake command, I got this:  https://pastebin.com/kHU6pp5i

**Comment by mateomaui** [comment]
I still haven't been able to get a successful CMake process. I thought maybe the issue was one of the CLI flags I'm using, so I just opened the directory in the CMake GUI to see what happens by default, and I got the exact same result: https://pastebin.com/S9JKFH9L

So... something isn't right here.

**Comment by mateomaui** [comment]
I figured out what was wrong: https://github.com/litucks/torzu/pull/21

**Pull request merged**
