### PR TITLE
Various build fixes

### PR DESCRIPTION
**Pull request by rtiangha**
A few things I encountered when playing around with the code.

* The first commit fixes some issues when compiling with `-DYUZU_USE_PRECOMPILED_HEADERS=OFF`.
* The second fixes a namespace naming conflict with one of the built in XCode libraries; easier just to change the name on this end.
* The third adds back the last copy of the compatibility database before the website went down so that part of the GUI is populated again.

### CODE REVIEW

**Comment by litucks** [comment]
Thanks for your contribution! One note about the compatibility database, I'd rather not restore that as it's already been extremely outdated when Yuzu got taken down.

**Comment by litucks** [comment]
PLEASE BE SURE to back up your repository, as a DMCA claim for this repo is VERY LIKELY incoming!!

In case this repository gets taken down before I've accepted your PR, please resubmit your PR on the new mirror repo!

It's going to be located at: https://codeberg.org/litucks/torzu

**Comment by mateomaui** [comment]
Yeah, don't worry about the compatibility database, yuzu devs were providing the guidance to just ignore it for quite a while. Things work now that didn't before and vice versa, it's not at all accurate.

**Comment by litucks** [comment]
I'll merge this manually without the compatibility database.

**Pull request merged**
